### ISSUE TITLE
Driver not loaded

### ISSUE THREAD

**Issue by BradenEH** [ETCLabs/ConductorLogFoo#1]
Installed on a project PC (Win10) and get "Error opening database - driver not loaded driver not loaded" when attempting to connect.

Confirmed IP address is correct.

Tried running with elevation.

![9f201432ca37ed547b0ab3f73c796c4cf2582ee0-14](https://user-images.githubusercontent.com/78758955/139874882-a9101885-77c7-467b-b078-11e86a89e90f.jpg)

**Comment by docsteer** [comment]
I have figured out the problem I think - the application doesn't install a Visual C++ runtime which is needed to connect to the database. I'll fix that in the installer but for now you can download it from https://www.microsoft.com/en-us/download/details.aspx?id=40784 - select the 32bit version (even if on 64bit windows)

**Comment by agbobeck** [comment]
Hi, just adding a vote here for this issue, it is still occurring (though not always) as of 2023-02-07. I will have to check my other computer, but a windows update may be involved. Win11 22H2

**Comment by docsteer** [comment]
This should now be fixed in 1.0.0.7 which I just released - I don't have an easy way to test though, so keep me posted if you see it again.
